corail-research/SeaPearl.jl

src/CP/constraints/setdiffsingleton.jl
This a fix for the `SetDiffSingleton` propagation error. I rearranged a bit the code which was a bit weird sometime, and added a `toRemove` buffer to avoid pruning values on the domain we are iterating on.
This PR should fix #122 .
=> fix: SetDiffSingleton propagation

Project.toml, src/CP/CP.jl, src/CP/constraints/algorithms/matching.jl, src/CP/core/model.jl, src/CP/core/search/dfs.jl, src/CP/core/search/ilds.jl, src/CP/core/search/search.jl, src/CP/variableselection/random.jl, src/MOI_wrapper/MOI_wrapper.jl, src/RL/nn_structures/flexGNN.jl, src/RL/nn_structures/flex_variable_output_gnn.jl, src/RL/nn_structures/nn_structures.jl, src/RL/nn_structures/weighted_graph_gat.jl, src/RL/representation/default/cp_layer/cp_layer.jl, src/SeaPearl.jl, src/datagen/coloring.jl, src/datagen/datagen.jl, src/datagen/knapsack.jl, src/datagen/nqueens.jl, src/datagen/tsptw.jl, src/experiment/experiment.jl, src/experiment/launch_experiment.jl, src/experiment/metrics/basicmetrics.jl, test/RL/RL.jl, test/trailer.jl
This is my proposition for refactoring SeaPearl.jl include order. 
It doesn't improve SeaPearl.jl compilation performance as described in https://docs.julialang.org/en/v1/manual/code-loading/, but makes the code cleaner and more understandable.
I also fix a little bug on the metrics plotting function :  `plotRewardVariation`
=> Refacto code

src/RL/nn_structures/fullfeaturedcpnn.jl, test/RL/nn_structures/fullfeaturedcpnn.jl
This PR add the possibility to use global features with the FullFeaturedCPNN structure.
It uses the same pattern as the classical CPNN.
=> Add globalFeatures and test to FullFeaturedCPNN

Project.toml
When removing the non critical dependencies I forgot to remove DataFrames.jl
=> removed DataFrames deps

Project.toml
Officialy adding @tomsander1998 @3rdCore and myself as authors + bumping to v0.3.0
=> Project.toml update

docs/src/CP/gecode_comparison.md, docs/src/CP/performance_test.md
Summary of the performance test  between Gecode and SeaPearl. The objective is to compare the execution time between SeaPearl and a commercial CP solver.
=> Add summary of the performance test 

src/CP/constraints/disjunctive.jl
Minor modification to make Disjunctive constraints more similar to the other constraints
=> Make type of earliestStartingTime more abstract

src/CP/variables/IntVar.jl, test/CP/variables/IntVar.jl
Closes #198.
The tests performed are quite simple, should we go further?
=> Override the - operator to easily define constraints of the form y= -x. 

src/CP/valueselection/classic/basicheuristic.jl, src/CP/valueselection/classic/random.jl, test/CP/valueselection/classic/basicheuristic.jl, test/CP/valueselection/classic/random.jl
Random value heuristic to replace those written in each SeaPearlZoo experiment.
Resolve #213.
=> Add RandomHeuristic for value

.github/workflows/documentation.yml, .gitignore, docs/make.jl, docs/src/CP/int_variable.md
Added yml file to automate the deployment of the doc created by Documenter.jl to the project's GitHub pages.
=> Added documentation automated deployment

Project.toml
Bumping julia version requirements.
=> Resolving compat format

.github/workflows/ci.yml
Removed duplicate pipeline run to address #277
=> Tentative change to avoid duplicating pipeline run

src/MOI_wrapper/utilities.jl, src/RL/representation/tsptw/tsptwstaterepresentation.jl
Very small code cleanup. Was aiming to trim dependencies, but none could be easily removed.
=> Reduce dependencies

src/experiment/training.jl
=> Fix minor spelling mistakes

src/CP/valueselection/learning/simplelearnedheuristic.jl, src/experiment/metrics/basicmetrics.jl
Misc. code cleanup and cosmetic improvements.
=> Dead code cleanup

src/datagen/coloring.jl, src/datagen/eternity2.jl, src/datagen/maxcut.jl, src/datagen/nqueens.jl, test/datagen/nqueens.jl
- Fix broken N-Queens instance generator
- Cleanup of various instance generators
=> Fix broken N-Queens generator

test/datagen/datagen.jl
=> Add test for eternity2 datagen

test/CP/CP.jl, test/RL/RL.jl, test/RL/representation/representation.jl, test/experiment/experiment.jl, test/runtests.jl
Include RL tests to the test pipeline.
=> Add RL tests

src/datagen/coloring.jl
minor change to one function call
=> Change function call to avoid deprecation warning

src/CP/constraints/equal.jl, src/CP/constraints/greaterorequal.jl, src/CP/constraints/lessorequal.jl, test/CP/constraints/equal.jl, test/CP/constraints/greaterorequal.jl, test/CP/constraints/lessorequal.jl
Implementation and test of new constraints :
- Less than
- Greater than 
- Greater or Equal 
- All equal
=> 1st constraint

src/parser/constraints/extension.jl, src/parser/constraints/group.jl, test/parser/constraints/constraints.jl, test/parser/constraints/data/extension/negative_table.xml, test/parser/constraints/data/extension/positive_table.xml, test/parser/constraints/data/extension/short_table.xml, test/parser/constraints/extension_parser.jl, test/runtests.jl
Add tests for extension parsing functions
=> Add tests for extension parsing

src/parser/parser.jl, src/parser/variables.jl, test/parser/variables/data/test_variable_array_different_domains.xml, test/parser/variables/variables_parser.jl
Variable parsing correction :
- domain can be different for subsets within a variable array, sometimes subset defined in "for" attribute is particular, (example : for="x[1..3][2][]"), all cases are treated and tested
=> variable parsing correction

src/CP/constraints/constraints.jl, src/CP/constraints/minimum.jl, src/parser/objective.jl, test/CP/constraints/constraints.jl, test/CP/constraints/minimum.jl, test/parser/objective/data/objective_maximum.xml, test/parser/objective/data/objective_minimum.xml, test/parser/objective/objective_parser.jl, test/runtests.jl
- Minimum constraint implemented and tested 
- Add new forms of objective functions with minimum and maximum 
- Compact formulation for objective parsing
=> minimum constraint + min/max objective

.github/workflows/ci.yml, Project.toml
=> Upgrade to julia 1.8

.github/workflows/scheduled-tests.yml
Add scheduled test to run XCSP3 tests every Friday night at 11 PM.
=> Add schedule XCSP3 tests

src/CP/constraints/element1dVar.jl, src/argparse_setting.jl, src/experiment/launch_experiment.jl, src/parser/constraints/constraints.jl, src/parser/constraints/element.jl, src/parser/constraints/group.jl, src/parser/constraints/intension.jl, src/parser/constraints/sum.jl, src/parser/parser.jl, src/parser/variables.jl
correct typo to make tom's experiments work
=> Tom experiments

src/output.jl
Hotfix to meet competition deadline
=> Fix parsing issue for XCSP3 instances
